ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'))
]

ecommerce/website/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.IndexView.as_view(),name = "index"),
    path('categories',views.categories,name="categories"),
    path('product/<slug>',views.ProductView.as_view(),name="product"),
    path('shoppingcart/<slug>',views.ViewCart,name="shoppingcart"),
    path('checkout',views.CheckoutView.as_view(),name="checkout"),
    path('contact',views.contact,name="contact"),
    path('add-to-cart/<slug>',views.add_to_cart,name="add-to-cart"),
    path('remove-from-cart/<slug>',views.remove_from_cart,name ="remove-from-cart"),
    path('payment/<str:payment_option>',views.Paymentfn,name="payment"),
    path('search/<str:tag>',views.search,name="search")
]

ecommerce/website/models.py
from django.db import models
from django.conf import settings
from django_mysql.models import ListCharField
from django.shortcuts import reverse
from django_countries.fields import CountryField

STATUS_CHOICES = (
    ('N','new'),
    ('P','popular'),
    ('S','sale')
)
CATEGORY_CHOICES = (
    ('MW','Mens Wear'),
    ('WW', 'Womens Wear'),
    ('EC', 'Electronics'),
    ('FW', 'Foot Wear')
)

class Item(models.Model):
    title = models.CharField(max_length=64)
    price = models.FloatField()
    category = models.CharField(choices=CATEGORY_CHOICES,max_length=2)
    status = models.CharField(choices=STATUS_CHOICES, max_length=1)
    tags = ListCharField(
          base_field= models.CharField(max_length=15),
          size = 10,
          max_length =(10 * 16)
    )
    slug = models.SlugField()
    description = models.TextField()


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("remove-from-cart",kwargs={
            'slug': self.slug
        })

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete= models.CASCADE)
    quantity = models.IntegerField(default=1)
    def __str__(self):
        return f"{self.item.title} x {self.quantity}"

    def get_total_price(self):
        return self.quantity * self.item.price


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress',on_delete=models.SET_NULL,blank=True,null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    slug = models.SlugField()
    dis_code = models.ForeignKey('DiscountCode',on_delete=models.SET_NULL,blank=True,null=True)

    def get_cart_url(self):
        return reverse("shoppingcart", kwargs={
            'slug': self.slug
        })

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_price()
        if self.dis_code:
            cut = 0
            for order_item in self.items.all():
                if order_item.item.category == self.dis_code.category:
                    cut = cut + (order_item.get_total_price() * ((self.dis_code.discount)/100))
            total = total - cut
        return total

    def __str__(self):
        return self.user.username

class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    street_address = models.CharField(max_length=100)
    city = models.CharField(max_length=30)
    zip = models.CharField(max_length=10)
    phone = models.CharField(max_length=15)
    country = CountryField(multiple=False)
    email = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.user.username},{self.city}'

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user  =  models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.SET_NULL,blank=True,null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class DiscountCode(models.Model):
    code = models.CharField(max_length=10)
    category = models.CharField(choices=CATEGORY_CHOICES,max_length=2)
    discount = models.IntegerField()

    def __str__(self):
        return self.code

ecommerce/website/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT_CHOICES = (
    ('P', 'PayPal'),
    ('C', 'Credit Card'),
    ('D', 'Cash on Delivery')
)
class CheckoutForm(forms.Form):
    street_address = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'ABC Street'}))
    country = CountryField(blank_label='(select country)').formfield(widget = CountrySelectWidget(attrs={'class':'country-select'}))
    city = forms.CharField()
    zip = forms.CharField()
    phone = forms.CharField()
    ship_to_different_address = forms.BooleanField(widget=forms.CheckboxInput())
    payment_method =forms.ChoiceField(widget=forms.RadioSelect(),choices=PAYMENT_CHOICES)
    email = forms.CharField()

ecommerce/website/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import messages
from .models import Item,OrderItem,Order,BillingAddress,Payment,DiscountCode
from .forms import CheckoutForm
from django.views.generic import ListView, DetailView, View
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
import django_mysql.models.lookups
import stripe
stripe.api_key = "sk_test_foRP96MM4gujWqr8Ggnwf06i00HZt23taZ"
P_key = "pk_test_tjoV1upnE5HnQ5PzoCAFbJoa00C2phujgW"


class IndexView(ListView):
    model = Item
    template_name = "website/index.html"

class ProductView(DetailView):
    model = Item
    template_name = "website/product.html"

def ViewCart(request,slug):

    order = Order.objects.get(slug=slug)
    items = order.items.all()
    if request.method == "GET":
        context ={
            'object' : order,
            'items' : items
        }
        return render(request, "website/shopping-cart.html", context)

    elif request.method == "POST":
        code = request.POST['code']
        discount_code = DiscountCode.objects.get(code = code)
        order.dis_code = discount_code
        context = {
            'object': order,
            'items': items
        }
        return render(request, "website/shopping-cart.html",context)


class CheckoutView(View):

    def get(self, *args, **kwargs):
        form = CheckoutForm()
        order = Order.objects.get(user=self.request.user,ordered=False)
        items = order.items.all()
        total = order.get_total()
        qty = order.items.count()

        context={
            'form':form,
            'items':items,
            'total':total,
            'qty': qty
        }
        return render(self.request, "website/check-out.html",context)

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user = self.request.user,ordered=False)
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                city = form.cleaned_data.get('city')
                zip = form.cleaned_data.get('zip')
                phone = form.cleaned_data.get('phone')
                country = form.cleaned_data.get('country')
                email = form.cleaned_data.get('email')
                payment_method = form.cleaned_data.get('payment_method')

                billing_address = BillingAddress(
                    user=self.request.user,
                    street_address=street_address,
                    city=city,
                    zip=zip,
                    phone=phone,
                    country=country,
                    email = email
                )
                billing_address.save()
                order.billing_address = billing_address
                order.save()
                if payment_method == 'C':
                    return redirect('payment', payment_option = 'card')
                elif payment_method == 'P':
                    return redirect('payment', payment_option = 'PayPal')
                else:
                    messages.warning(self.request,"Failed Checkout")
                    return redirect('checkout')

        except ObjectDoesNotExist:
            return redirect('shoppingcart')

def Paymentfn(request, payment_option = 'card'):

    order = Order.objects.get(user=request.user, ordered=False)
    amount = int(order.get_total())
    name = order.user.username
    address = order.billing_address.street_address
    email = order.billing_address.email
    city = order.billing_address.city
    payment_option = payment_option

    if request.method == 'GET':
        intent = stripe.PaymentIntent.create(
            amount=amount * 100,
            currency='inr',
            payment_method_types=['card'],
            description="Test payment"
        )
        context = {
            'Publishable_key': P_key,
            'customer_email': email,
            'intent_id': intent.id,
            'customer_address': address,
            'customer_name': name,
            'city': city
        }
        return render(request, "website/payment.html", context)

    elif request.method == 'POST':
        intent_id = request.POST['intent_id']
        payment_method_id = request.POST['payment_method_id']
        stripe.api_key = "sk_test_foRP96MM4gujWqr8Ggnwf06i00HZt23taZ"
        stripe.PaymentIntent.modify(
            intent_id,
            payment_method=payment_method_id
        )
        stripe.PaymentIntent.confirm(intent_id)
        # create payment
        payment = Payment()
        payment.stripe_charge_id = intent_id
        payment.user = request.user
        payment.amount = amount
        payment.save()
        # assign payment to order
        order.ordered = True
        order.payment = payment
        order.save()

        messages.success(request, "Your order was placed successfully")
        return redirect("/")




def categories(request):
    return render(request,"website/categories.html")

def checkout(request):
    return render(request,"website/check-out.html")

def contact(request):
    return render(request,"website/contact.html")

def add_to_cart(request,slug):
    item = get_object_or_404(Item,slug= slug)
    order_item, created = OrderItem.objects.get_or_create(item=item,user = request.user,ordered = False)
    order_qs = Order.objects.filter(user = request.user,ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "Item quantity updated")
        else:
            messages.info(request,"Item was added to your cart")
            order.items.add(order_item)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user,ordered_date=ordered_date,slug=request.user.username)
        order.items.add(order_item)
        messages.info(request, "Item was added to your cart")

    return redirect("/")


def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item = get_object_or_404(OrderItem, item=item)
    order_item.delete()
    messages.info(request, "Item removed from cart!")

    return redirect("shoppingcart")

def search(request, tag):
    items = Item.objects.all()
    ITEMS = []
    for item in items:
        tag_list = item.tags
        if tag in tag_list:
            ITEMS.append(item)
    context = {
        'items' : ITEMS,
        'tag':tag
    }
    return render(request,"website/search.html",context)

ecommerce/website/templates/website/check-out.html
{% extends "website/base.html" %}
{% block body %}
{% load crispy_forms_tags %}

    <!-- Page Add Section Begin -->
    <section class="page-add">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="page-breadcrumb">
                        <h2>Checkout<span>.</span></h2>
                    </div>
                </div>
                <div class="col-lg-8">
                    <img src="static/img/add.jpg" alt="">
                </div>
            </div>
        </div>
    </section>
    <!-- Page Add Section End -->

    <!-- Cart Total Page Begin -->
        <div class="container">
            <div class="row">
            <div class="col-6 jumbotron">
                <h3>Your Information</h3>
                <br>
                <form method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn-success btn-lg" type="submit">
                    Submit Payment</button>
            </form>
            </div>
                <div class="col-1"></div>
                <div class="col-3">
                    <div class="jumbotron text-center">
                            <div class="cart-item">
                                <span>Product(s)</span>
                                {% for item in items %}
                                <p class="product-name">{{item.item.title}}</p>
                                {% endfor %}
                            </div>
                            <div class="cart-item">
                                <span>Price</span>
                                <p>&#x20B9;{{total}}</p>
                            </div>
                            <div class="cart-item">
                                <span>Quantity</span>
                                <p>{{qty}}</p>
                            </div>
                            <div class="cart-item">
                                <span>Shipping</span>
                                <p>FREE</p>
                            </div>

                            <div class="cart-total">
                                <span>Total</span>
                                <p>&#x20B9;{{total}}</p>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
<br>
    <!-- Cart Total Page End -->

{% endblock %}

ecommerce/website/templates/website/index.html
{% extends "website/base.html" %}
{% load static %}
{% block body %}

    <section class="latest-products spad">
        <div class="container">
            <div class="product-filter">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="section-title">
                            <h2>Latest Products</h2>
                        </div>
                        <ul class="product-controls">
                            <li data-filter="*">Foot Wear</li>
                            <li data-filter=".dresses">Electronics</li>
                            <li data-filter=".bags">Mens Wear</li>
                            <li data-filter=".shoes">Womens Wear</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row" id="product-list">
                {% for item in object_list %}
                <div class="col-lg-3 col-sm-6">
                    <div class="single-product-item">
                        <figure>
                            <a href="{{item.get_absolute_url}}"><img src="static/img/products/{{item.title}}1.jpg" alt=""></a>
                            <div class="p-status {{item.get_status_display}}">{{item.get_status_display}}</div>
                        </figure>
                        <div class="product-text">
                            <h6>{{item.title}}</h6>
                            <p>&#x20B9; {{item.price}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Latest Product End -->
    <!-- Features Section Begin -->
    <section class="features-section spad">
        <div class="features-ads">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="single-features-ads first">
                            <img src="{%static 'img/icons/f-delivery.png' %}" alt="">
                            <h4>Free shipping</h4>
                            <p>Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Vesti bulum mal
                                esuada aliquet libero viverra cursus. </p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="single-features-ads second">
                            <img src="{% static 'img/icons/coin.png' %}" alt="">
                            <h4>100% Money back </h4>
                            <p>Urna quam, euismod sit amet mollis quis, vestibulum quis velit. Vesti bulum mal esuada
                                aliquet libero viverra cursus. </p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="single-features-ads">
                            <img src="{% static 'img/icons/chat.png' %}" alt="">
                            <h4>Online support 24/7</h4>
                            <p>Urna quam, euismod sit amet mollis quis, vestibulum quis velit. Vesti bulum mal esuada
                                aliquet libero viverra cursus. </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Features Box -->
        <div class="features-box">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="single-box-item first-box">
                                    <img src="{% static 'img/f-box-1.jpg' %}" alt="">
                                    <div class="box-text">
                                        <span class="trend-year">2019 Party</span>
                                        <h2>Jewelry</h2>
                                        <span class="trend-alert">Trend Alert</span>
                                        <a href="#" class="primary-btn">See More</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="single-box-item second-box">
                                    <img src="{% static 'img/f-box-2.jpg' %}" alt="">
                                    <div class="box-text">
                                        <span class="trend-year">2019 Trend</span>
                                        <h2>Footwear</h2>
                                        <span class="trend-alert">Bold & Black</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="single-box-item large-box">
                            <img src="{% static 'img/f-box-3.jpg' %}" alt="">
                            <div class="box-text">
                                <span class="trend-year">2019 Party</span>
                                <h2>Collection</h2>
                                <div class="trend-alert">Trend Allert</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Features Section End -->

    <!-- Latest Product Begin -->


    <!-- Lookbok Section Begin -->
    <section class="lookbok-section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 offset-lg-1">
                    <div class="lookbok-left">
                        <div class="section-title">
                            <h2>2019 <br />#lookbook</h2>
                        </div>
                        <p>Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Vestibulum malesuada
                            aliquet libero viverra cursus. Aliquam erat volutpat. Morbi id dictum quam, ut commodo
                            lorem. In at nisi nec arcu porttitor aliquet vitae at dui. Sed sollicitudin nulla non leo
                            viverra scelerisque. Phasellus facilisis lobortis metus, sit amet viverra lectus finibus ac.
                            Aenean non felis dapibus, placerat libero auctor, ornare ante. Morbi quis ex eleifend,
                            sodales nulla vitae, scelerisque ante. Nunc id vulputate dui. Suspendisse consectetur rutrum
                            metus nec scelerisque. s</p>
                        <a href="#" class="primary-btn look-btn">See More</a>
                    </div>
                </div>
                <div class="col-lg-5 offset-lg-1">
                    <div class="lookbok-pic">
                        <img src="{% static 'img/lookbok.jpg' %}" alt="">
                        <div class="pic-text">fashion</div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Lookbok Section End -->

    <!-- Logo Section Begin -->
    <div class="logo-section spad">
        <div class="logo-items owl-carousel">
            <div class="logo-item">
                <img src="{% static 'img/logos/logo-1.png' %}" alt="">
            </div>
            <div class="logo-item">
                <img src="{% static 'img/logos/logo-2.png' %}" alt="">
            </div>
            <div class="logo-item">
                <img src="{% static 'img/logos/logo-3.png' %}" alt="">
            </div>
            <div class="logo-item">
                <img src="{% static 'img/logos/logo-4.png' %}" alt="">
            </div>
            <div class="logo-item">
                <img src="{% static 'img/logos/logo-5.png' %}" alt="">
            </div>
        </div>
    </div>
    <!-- Logo Section End -->
    {% endblock %}
    <!-- Footer Section Begin -->

ecommerce/website/templates/website/itemlist.html
{% extends "website/layout.html" %}

{% block body %}
<div>All items:</div>
{% for item in items %}
<p>{{item}}</p>
{% endfor %}
{% endblock %}

ecommerce/website/templates/website/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ecommerce</title>
    {% block head %}
    {% endblock %}
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

ecommerce/website/templates/website/product.html
{% extends "../website/base.html" %}

{% block head %}
<base href="../" target="_blank">
{% endblock %}

    <!-- Page Add Section Begin -->
<!--    <section class="page-add">-->
<!--        <div class="container">-->
<!--            <div class="row">-->
<!--                <div class="col-lg-4">-->
<!--                    <div class="page-breadcrumb">-->
<!--                        <h2>Shirts<span>.</span></h2>-->
<!--                        <a href="#">Home</a>-->
<!--                        <a href="#">Dresses</a>-->
<!--                        <a class="active" href="#">Night Dresses</a>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-lg-8">-->
<!--                    <img src="static/img/add.jpg" alt="">-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </section>-->
    <!-- Page Add Section End -->

    <!-- Product Page Section Beign -->
{% block body %}
    <section class="product-page">
        <div class="container">
            <div class="product-control">
                <a href="#">Previous</a>
                <a href="#">Next</a>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="product-slider owl-carousel">
                        <div class="product-img">
                            <figure>
                                <img src="static/img/product/{{object.title}}1.jpg" alt="">
                                <div class="p-status {{object.get_status_display}}">{{object.get_status_display}}</div>
                            </figure>
                        </div>
                        <div class="product-img">
                            <figure>
                                <img src="static/img/product/{{object.title}}2.jpg" alt="">
                                <div class="p-status {{object.get_status_display}}">{{object.get_status_display}}</div>
                            </figure>
                        </div>
                    </div>
                    
                </div>
                <div class="col-lg-6">
                    <div class="product-content">
                        <h2>{{object.title}}</h2>
                        <div class="pc-meta">
                            <h5>&#x20B9; {{object.price}}</h5>
                            <div class="rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                        </div>
                        <p>{{object.description}}</p>
                        <ul class="tags">
                            <li><span>Category :</span> {{object.get_category_display}}</li>
                            <li><span>Tags :</span>{% for tag in object.tags %}
                                <button class="btn btn-link btn-sm" onclick= location.href="search/{{tag}}">{{tag}}</button>{% endfor %}</li>
                        </ul>
                        <div class="product-quantity">
                            <div class="pro-qty">
                                <input type="text" value="1">
                            </div>
                        </div>
                        {% if user.is_authenticated %}
                        <a href="{{ object.get_add_to_cart_url }}" class="primary-btn pc-btn">Add to cart</a>
                        {% else %}
                        <a href="{{ object.get_add_to_cart_url }}" class="btn primary-btn pc-btn disabled" role="button">Add to cart</a>
                        {% endif %}
                        <ul class="p-info">
                            <li>Product Information</li>
                            <li>Reviews</li>
                            <li>Product Care</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Product Page Section End -->

    <!-- Related Product Section Begin -->
    <section class="related-product spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="section-title">
                        <h2>Related Products</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="single-product-item">
                        <figure>
                            <a href="#"><img src="static/img/products/img-1.jpg" alt=""></a>
                            <div class="p-status">new</div>
                        </figure>
                        <div class="product-text">
                            <h6>Green Dress with details</h6>
                            <p>$22.90</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single-product-item">
                        <figure>
                            <a href="#"><img src="static/img/products/img-2.jpg" alt=""></a>
                            <div class="p-status sale">sale</div>
                        </figure>
                        <div class="product-text">
                            <h6>Yellow Maxi Dress</h6>
                            <p>$25.90</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single-product-item">
                        <figure>
                            <a href="#"><img src="static/img/products/img-3.jpg" alt=""></a>
                            <div class="p-status">new</div>
                        </figure>
                        <div class="product-text">
                            <h6>One piece bodysuit</h6>
                            <p>$19.90</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single-product-item">
                        <figure>
                            <a href="#"><img src="static/img/products/img-4.jpg" alt=""></a>
                            <div class="p-status popular">popular</div>
                        </figure>
                        <div class="product-text">
                            <h6>Blue Dress with details</h6>
                            <p>$35.50</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Related Product Section End -->
{% endblock %}

ecommerce/website/templates/website/search.html
{% extends "website/base.html" %}
{% block head %}
<base href="../" target="_blank">
{% endblock %}
{% block body %}
<div class="container">
    <div class="page-header text-center">
<h2>'{{tag}}'  PRODUCTS:</h2>
</div>
        <br>
    <div class="row" id="product-list">
                {% for item in items %}
                <div class="col-lg-3 col-sm-6">
                    <div class="single-product-item">
                        <figure>
                            <a href="{{item.get_absolute_url}}"><img src="static/img/products/{{item.title}}1.jpg" alt=""></a>
                            <div class="p-status {{item.get_status_display}}">{{item.get_status_display}}</div>
                        </figure>
                        <div class="product-text">
                            <h6>{{item.title}}</h6>
                            <p>&#x20B9; {{item.price}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
</div>
{% endblock %}